### ISSUE TITLE
Rendering Screen / NoSuchMethodError

### ISSUE THREAD

**Issue by spannerman79** [LatvianModder/EMC_Condenser#7]
Crashlog https://paste.ee/p/reJ2k

**Comment by LatvianModder** [comment]
This can be fixed by updating EE3 (ir downgrading, cant remeber, Pahi changed his API very often)

**Comment by spannerman79** [comment]
Currently running EquivalentExchange3-1.7.10-0.3.507.jar
Which did you build EMC Condenser against? ( http://minecraft.curseforge.com/mc-mods/65509-ee3/files )

**Comment by LatvianModder** [comment]
I think its 0.3.496

**Comment by LatvianModder** [comment]
I will update tho
